apps/rsvp_web/lib/rsvp_web/router.ex
defmodule RsvpWeb.Router do
  use RsvpWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RsvpWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/events", EventController, :list
    get "/events/new", EventController, :create
    post "/events/new", EventController, :add
    get "/events/:id", EventController, :show
    post "/events/:id/reserve", EventController, :reserve


    get "/login", LoginController, :index
    post "/login", LoginController, :login

  end

  # Other scopes may use custom stacks.
  # scope "/api", RsvpWeb do
  #   pipe_through :api
  # end
end

apps/rsvp_web/lib/plugs/authorized_plug.ex
defmodule RsvpWeb.AuthorizedPlug do
    import Plug.Conn
    # to use redirect we need to import the phoenix controller.
    import Phoenix.Controller

    def init(options) do
        options
    end

    def call(conn, _name) do
        user_name = conn.cookies["user_name"]
        authorize_user(conn, user_name)
    end

    defp authorize_user(conn, nil) do
        conn
        |> redirect(to: "/login")
        |> halt # prevents call more plugs
    end

    defp authorize_user(conn, user_name) do
        conn
    end

end

apps/rsvp_web/lib/rsvp_web/controllers/event_controller.ex
defmodule RsvpWeb.EventController do
    use RsvpWeb, :controller
    alias Rsvp.Events
    plug RsvpWeb.AuthorizedPlug, "create" when action in [:create]

    def show(conn, %{"id" => id}) do
        event = Events.get_event!(id)
        render conn, "details.html", event: event
    end

    def list(conn, _params) do
        events = Events.list_events()
        render conn, "list.html", events: events
    end

    def create(conn, %{errors: errors}) do
        render conn, "create.html", changeset: errors
    end

    def create(conn, _params) do
        changeset = Events.Event.changeset(%Events.Event{}, %{}) |> IO.inspect
        render conn, "create.html", changeset: changeset
    end

    def add(conn, %{"event" => event}) do
        # Fix the date adding seconds it is possible
        # creating a new update to our Map structure.
        event = Map.update!(event, "date", fn d -> d <> ":00" end)

        case Events.create_event event do
            {:ok, %{id: id}} -> redirect conn, to: event_path(conn, :show, id)
            {:error, reasons} -> create conn, %{errors: reasons}
        end
    end

    # def list_for_location(conn, %{"location" => location}) do
    #     events = Events.get_all_for_location(location)
    #     render conn, "list.html", events: events
    # end

    def reserve(conn, %{"id" => id, "reservation" => %{"quantity" => quantity}}) do
        {:ok, event} = Events.decrease_quantity(id, quantity)
        RsvpWeb.EventChannel.send_update(event)

        redirect conn, to: event_path(conn, :show, id)
    end

end

apps/rsvp_web/lib/rsvp_web/controllers/login_controller.ex
defmodule RsvpWeb.LoginController do
    use RsvpWeb, :controller

    def index(conn, _) do
        render conn, "login.html"
    end

    def login(conn, %{"login" => %{"username" => name}}) do
        expiration = 60*60*24*7
        conn
        |> Plug.Conn.put_resp_cookie("user_name", name, max_age: expiration)
        |> redirect(to: "/")
    end
end

apps/rsvp_web/lib/rsvp_web/controllers/page_controller.ex
defmodule RsvpWeb.PageController do
  use RsvpWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

apps/rsvp_web/lib/rsvp_web/views/error_view.ex
defmodule RsvpWeb.ErrorView do
  use RsvpWeb, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

apps/rsvp_web/lib/rsvp_web/views/event_view.ex
defmodule RsvpWeb.EventView do
    use RsvpWeb, :view

    def format_date(date) do
       {{y, m, d}, _} = Elixir.NaiveDateTime.to_erl(date)
       "#{m}/#{d}/#{y}"
    end
end

apps/rsvp_web/lib/rsvp_web/views/layout_view.ex
defmodule RsvpWeb.LayoutView do
  use RsvpWeb, :view
end

apps/rsvp_web/lib/rsvp_web/views/login_view.ex
defmodule RsvpWeb.LoginView do
  use RsvpWeb, :view
end

apps/rsvp_web/lib/rsvp_web/views/page_view.ex
defmodule RsvpWeb.PageView do
  use RsvpWeb, :view
end

apps/rsvp_web/lib/rsvp_web/views/shared_view.ex
defmodule RsvpWeb.SharedView do
    use RsvpWeb, :view
end

apps/rsvp_web/lib/rsvp_web/templates/event/create.html.eex
<h1>Add new event</h1>
<%= form_for @changeset, event_path(@conn, :add), fn f -> %>
    <div class="form-group">
        <%= label f, :title, "Title" %>
        <%= text_input f, :title, class: "form-control" %>
        <%= error_tag f, :title %>
    </div>

    <div class="form-group">
        <%= label f, :location, "Location" %>
        <%= text_input f, :location, class: "form-control" %>
        <%= error_tag f, :location %>
    </div>

    <div class="form-group">
        <%= label f, :date, "Date & Time" %>
        <%= text_input f, :date, class: "form-control", type: "datetime-local" %>
        <%= error_tag f, :date %>
    </div>

    <div class="form-group">
        <%= label f, :description, "Description" %>
        <%= textarea f, :description, class: "form-control", rows: 5 %>
        <%= error_tag f, :description %>
    </div>

    <%= submit "Add", class: "btn btn-primary pull-right" %>
<% end %>

apps/rsvp_web/lib/rsvp_web/templates/event/details.html.eex
<h1>
    <%= @event.title %> <small><%= @event.location %></small>
</h1>
<h3><%= format_date @event.date %></h3>
<h4>Available Spots: <span id="quantity" class="quantity"><%= @event.quantity_available %></span></h4>

<%= form_for @conn, event_path(@conn, :reserve, @event.id), [as: :reservation, class: "form-inline"], fn f -> %>
    <div class="form-group">
        <%= label f, :quantity, "Quantity" %>
        <%= number_input f, :quantity, class: "form-control", min: 1 %>
    </div>
    <%= submit "Reserve", class: "btn btn-primary pull-right" %>
<% end %>

<span id="id" data-id="<%= @event.id %>"></span>

apps/rsvp_web/lib/rsvp_web/templates/event/list.html.eex
<h1>All Events</h1>
<a href="<%= event_path(@conn, :create) %>" class="btn btn-primary pull-right">Add Event</a>
<%= render RsvpWeb.SharedView, "count.html", list: @events %>
<div class="list-group">
    <%= for e <- @events do %>
        <%= render "summary.html", event: e, conn: @conn %>
    <% end %>
</div>

apps/rsvp_web/lib/rsvp_web/templates/event/summary.html.eex
<a href="<%= event_path(@conn, :show, @event.id) %>">
    <div class="list-group-item">
        <h4 class="list-group-item-heading"><%= @event.title %></h4>
        <span>
            <span clas="text-muted"><%= @event.location %></span>
            <span clas="pull-right">
                <strong><%= format_date @event.date %></strong>
            </span>
        </span>
    </div>
</a>

apps/rsvp_web/lib/rsvp_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Rsvp!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav role="navigation">
      <ul class="nav nav-pills col-xs-offset-7">
        <li><a href="/">Home</a></li>
        <li><a href="<%= event_path(@conn, :list) %>">Events</a></li>
        <li><a href="<%= login_path(@conn, :index) %>">Login</a></li>
      </ul>
    </nav>
    <div class="container">
      <header class="header" style="text-align: center">
        <span class="title">RSVP</span>
        <span class="sub-title">Your online directory of events</h4>
        <%= if @conn.cookies["user_name"] do %>
          <span>
            Hello, <%= @conn.cookies["user_name"] %>
          </span>
        <% end %>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

apps/rsvp_web/lib/rsvp_web/templates/login/login.html.eex
<%= form_for @conn, login_path(@conn, :login), [as: :login], fn f -> %>
    <%= text_input f, :username %>
    <%= submit "Login" %>
<% end %>

apps/rsvp_web/lib/rsvp_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

apps/rsvp_web/lib/rsvp_web/templates/shared/count.html.eex
<h3>Total Counts: <%= Enum.count @list %></h3>